version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: clean-arch-db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: go.Dockerfile
    volumes:
    - .:/app
    depends_on:
      - db
networks:
  default:
    external:
      name: "${DOCKER_NETWORK}"