version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: my-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: go.Dockerfile
    volumes:
    - .:/app
    depends_on:
      - db
networks:
  default:
    external:
      name: "${DOCKER_NETWORK}"